name: Ubuntu Build

# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3

      # fix: cannot find -lunwind: No such file or directory
      # https://blog.csdn.net/weixin_52000358/article/details/146281075
      - name: Setup
        run: |
          sudo apt-get -y install libunwind-dev libstdc++-12-dev
          ./setup.sh

      - name: Build AirLib
        run: |
          ./build.sh

      - name: Build ROS2 Wrapper
        if: matrix.os == 'ubuntu-22.04'
        run: |
          chmod +x ./tools/install_ros2_deps.sh
          ./tools/install_ros2_deps.sh
          source /opt/ros/*/setup.bash
          cd ros2
          colcon build --cmake-args -DCMAKE_C_COMPILER=gcc-11 --cmake-args -DCMAKE_CXX_COMPILER=g++-11
          
      - name: Build GazeboDrone
        run: |
          sudo apt-get install -qq ros-humble-gazebo-ros gcc-11 g++-11
          ./clean.sh && ./build.sh --gcc
          cd GazeboDrone
          mkdir build && cd build
          cmake -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11 ..
          make
